---
title: "test"
output: html_document
date: "2023-07-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(gganimate)
library(usmap)
library(mapview)
library(maps)
library(mapdata)
library(maptools)  #for shapefiles
library(scales)  #for transparency

```

```{r}

lobsterlist <- c(`wtcpue.Homarus.americanus`, `year`, `lat`, `wtcpue.Dichelopandalus.leptocerus`,
    `wtcpue.Asterias.rubens`, `wtcpue.Crossaster.papposus` ,
    `wtcpue.Cucumaria.frondosa` , `wtcpue.Enchelyopus.cimbrius` ,
    `wtcpue.Dfo.bryozoans.ectoprocta` , `wtcpue.Hippoglossus.hippoglossus` ,
    region , `wtcpue.Hippoglossoides.platessoides`, `wtcpue.Arctica.islandica` ,
    `wtcpue.Hydrozoa` , `wtcpue.Dfo.gorgonocephalidae.Asteronychidae.f.(6300)` ,
    `wtcpue.Leptasterias`, `wtcpue.Neptunea.lyrata`)

# Filter and select only lobster
trawlnewdata <- data6 |>
  select(year, lat, region, lon, depth, `wtcpue.Homarus americanus`, `wtcpue.Dichelopandalus leptocerus`,
    `wtcpue.Asterias rubens`, `wtcpue.Crossaster papposus` ,
    `wtcpue.Cucumaria frondosa` , `wtcpue.Enchelyopus cimbrius` ,
    `wtcpue.Dfo:bryozoans ectoprocta` , `wtcpue.Hippoglossus hippoglossus` ,
    `wtcpue.Hippoglossoides platessoides`, `wtcpue.Arctica islandica` ,
    `wtcpue.Hydrozoa` , `wtcpue.Dfo:gorgonocephalidae,Asteronychidae f.(6300)` ,
    `wtcpue.Leptasterias`, `wtcpue.Neptunea lyrata`)

glimpse(data6)

```

```{r}
trawldata <- trawlnewdata |>
  mutate(latmodify1 = as.double(str_sub(lat, 0, 2))) |>
  mutate(latmodify2 = lat - latmodify1) |>
  mutate(latmodify3 = case_when(
                      latmodify2 >= 0 & latmodify2 < 0.25 ~ 0.125,
                      latmodify2 >= 0.25 & latmodify2 < 0.5 ~ 0.375,
                      latmodify2 >= 0.5 & latmodify2 < 0.75 ~ 0.625,
                      latmodify2 >= 0.75 & latmodify2 < 1 ~ 0.875)) |>
  mutate(lat_new = latmodify1 + latmodify3)|>
  mutate(lonmodify1 = as.double(str_sub(lon, 0, 4))) |>
  mutate(lonmodify2 = lon - lonmodify1) |>
  mutate(lonmodify3 = case_when(
                      lonmodify2 <= -0 & lonmodify2 > -0.25 ~ -0.125,
                      lonmodify2 <= -0.25 & lonmodify2 > -0.5 ~ -0.375,
                      lonmodify2 <= -0.5 & lonmodify2 > -0.75 ~ -0.625,
                      lonmodify2 <= -0.75 & lonmodify2 > -1 ~ -0.875)) |>
  mutate(lon_new = lonmodify1 + lonmodify3) |>
  select(year, lat_new, lon_new, region, depth, `wtcpue.Homarus americanus`, `wtcpue.Dichelopandalus leptocerus`,
    `wtcpue.Asterias rubens`, `wtcpue.Crossaster papposus` ,
    `wtcpue.Cucumaria frondosa` , `wtcpue.Enchelyopus cimbrius` ,
    `wtcpue.Dfo:bryozoans ectoprocta` , `wtcpue.Hippoglossus hippoglossus` ,
    `wtcpue.Hippoglossoides platessoides`, `wtcpue.Arctica islandica` ,
    `wtcpue.Hydrozoa` , `wtcpue.Dfo:gorgonocephalidae,Asteronychidae f.(6300)` ,
    `wtcpue.Leptasterias`, `wtcpue.Neptunea lyrata`) |>
  unite("lon_lat", lon_new:lat_new, sep= ",",remove = FALSE) |>
  separate(lon_lat, into = c("lon", "lat"), sep = ",", convert = TRUE) |>
  select(year, lat, lon, region, depth, `wtcpue.Homarus americanus`, `wtcpue.Dichelopandalus leptocerus`,
    `wtcpue.Asterias rubens`, `wtcpue.Crossaster papposus` ,
    `wtcpue.Cucumaria frondosa` , `wtcpue.Enchelyopus cimbrius` ,
    `wtcpue.Dfo:bryozoans ectoprocta` , `wtcpue.Hippoglossus hippoglossus` ,
    `wtcpue.Hippoglossoides platessoides`, `wtcpue.Arctica islandica` ,
    `wtcpue.Hydrozoa` , `wtcpue.Dfo:gorgonocephalidae,Asteronychidae f.(6300)` ,
    `wtcpue.Leptasterias`, `wtcpue.Neptunea lyrata`) |>
  pivot_longer(cols = `wtcpue.Homarus americanus`: `wtcpue.Dichelopandalus leptocerus`:
    `wtcpue.Asterias rubens`: `wtcpue.Crossaster papposus` :
    `wtcpue.Cucumaria frondosa`: `wtcpue.Enchelyopus cimbrius` :
    `wtcpue.Dfo:bryozoans ectoprocta` : `wtcpue.Hippoglossus hippoglossus` :
    `wtcpue.Hippoglossoides platessoides`: `wtcpue.Arctica islandica` :
    `wtcpue.Hydrozoa` : `wtcpue.Dfo:gorgonocephalidae,Asteronychidae f.(6300)` :
    `wtcpue.Leptasterias`: `wtcpue.Neptunea lyrata`,
    names_to = 'spp', values_to = 'density') |>
  summarise(density_avg = mean(density), depth_avg = mean(depth), .by = c(year, lat, lon, region, spp)) |>
  pivot_wider(
    names_from = spp,
    values_from = density_avg
  )

# save(trawldata, file = "datablocked.RData")

```
```{r}
trawldata_transformed <- 
  
  trawldata |>
  select(year, lon, lat, depth_avg, `wtcpue.Homarus americanus`, 
         `wtcpue.Crossaster papposus`, `wtcpue.Dfo:bryozoans ectoprocta`, `wtcpue.Neptunea lyrata`)

%>%
  pivot_longer(cols = `wtcpue.Homarus americanus`:`wtcpue.Neptunea lyrata`,
               names_to = 'spp', values_to = 'density') %>%
  summarise(avgden = mean(density), .by = c(spp, depth_avg)) |>
  filter(spp == 'wtcpue.Homarus americanus') |>
  ggplot(aes(x = depth_avg, y = avgden)) + 
  geom_point() 




# Create the density plot with multiple curves
ggplot(trawldata_transformed, aes(x = depth_avg, y = avgden, color = spp, level = spp)) + 
  geom_density(aes(y = after_stat(count)), alpha = 0.5) +  # Use y = ..density.. aesthetic
  labs(title = "Species Distribution in Terms of Average Depth",
       x = "Average Depth", y = "Density",
       color = "Species") +
  theme_minimal() 



  
  # Scatter plot with overlapping points and depth facetting
ggplot(aes(x = lon, y = lat)) +
  geom_point(aes(size = `wtcpue.Homarus americanus`, color = "Homarus americanus"), alpha = 0.5) +
  geom_point(aes(size = `wtcpue.Crossaster papposus`, color = "Crossaster papposus"), alpha = 0.5) +
  geom_point(aes(size = `wtcpue.Dfo:bryozoans ectoprocta`, color = "Dfo:bryozoans ectoprocta"), alpha = 0.5) +
  geom_point(aes(size = `wtcpue.Neptunea lyrata`, color = "Neptunea lyrata"), alpha = 0.5) +
  scale_size_continuous(name = "Abundance", breaks = c(0, 100, 200, 300, 400), labels = scales::comma) +
  scale_color_manual(values = c("Homarus americanus" = "red", 
                                "Crossaster papposus" = "blue",
                                "Dfo:bryozoans ectoprocta" = "green",
                                "Neptunea lyrata" = "purple")) +
  labs(title = "Species Spatial Distribution by Depth",
       x = "Longitude", y = "Latitude",
       color = "Species") +
  theme_minimal() +
  facet_wrap(~ depth_avg, ncol = 2)+  # Facet by depth levels with 2 columns
 coord_cartesian(xlim = c(-80, -55), ylim = c(32, 48))
```


```{r}

us_map <- map_data("world")
us_borders <- map_data("state")

trawlplot <- trawldata |>
  unite("lon_lat", lon:lat, sep= ",",remove = FALSE) |>
  summarise(avgwtc_all = mean(avgwtc), .by = lon_lat) |>
  separate(lon_lat, into = c("lon", "lat"), sep = ",", convert = TRUE) |>
  mutate(lobtest = if_else(avgwtc_all > 0, "WTCPUE > 0", "Trawl Area")) |>
  ggplot(aes(x = lon, y = lat, fill = lobtest)) + 
  geom_polygon(data = us_map, aes(x = long, y = lat, group = group), fill = "darkgray", color = "black")+
  geom_polygon(data = us_borders, aes(x = long, y = lat, group = group), fill = "lightgray", color = "darkgreen")+
  geom_tile(alpha = 0.8) +
  coord_cartesian(xlim = c(-185, -50), ylim = c(25, 70))+
  theme(legend.position = 'top') + 
  labs(fill = "") + 
  labs(fill = "", x = "Longitude (in degrees)", y = "Latitude (in degrees)") + 
  geom_text(x = -75, y = 45, label = "USA", color = "black", size = 4, fontface = "bold") +
  geom_text(x = -65, y = 45, label = "Canada", color = "black", size = 4, fontface = "bold")




```

```{r}
trawlzoomplot <- trawldata |>
  unite("lon_lat", lon:lat, sep= ",",remove = FALSE) |>
  mutate(avgwtc = `wtcpue.Homarus americanus`) |>
  summarise(avgwtc_all = mean(avgwtc), .by = lon_lat) |>
  separate(lon_lat, into = c("lon", "lat"), sep = ",", convert = TRUE) |>
  mutate(lobtest = if_else(avgwtc_all > 0, "Lobster WTCPUE > 0", "Trawl Area")) |>
  ggplot(aes(x = lon, y = lat, fill = lobtest)) + 
  geom_polygon(data = us_map, aes(x = long, y = lat, group = group), fill = "darkgray", color = "black")+
  geom_polygon(data = us_borders, aes(x = long, y = lat, group = group), fill = "lightgray", color = "darkgreen")+
  geom_tile(alpha = 0.8) +
  coord_cartesian(xlim = c(-80, -55), ylim = c(32, 48))+
  theme(legend.position = 'right') + 
  labs(fill = "", x = "Longitude (in degrees)", y = "Latitude (in degrees)") + 
  geom_text(x = -75, y = 41.5, label = "The United States", color = "black", size = 8, 
            fontface = "bold", angle = 40) +
  geom_text(x = -75, y = 46.5, label = "Canada", color = "black", size = 8, fontface = "bold")

trawlzoomplot

```


```{r}
trawlzoomplot2 <- trawlnewdata |>
  unite("lon_lat", `lon`:`lat`, sep= ",",remove = FALSE) |>
  mutate(avgwtc = `wtcpue.Homarus americanus`) |>
  summarise(avgwtc_all = mean(avgwtc), .by = lon_lat) |>
  separate(lon_lat, into = c("lon", "lat"), sep = ",", convert = TRUE) |>
  mutate(lobtest = if_else(avgwtc_all > 0, "Lobster WTCPUE > 0", "Trawl Area")) |>
  ggplot(aes(x = lon, y = lat, fill = lobtest)) + 
  geom_polygon(data = us_map, aes(x = long, y = lat, group = group), fill = "darkgray", color = "black")+
  geom_polygon(data = us_borders, aes(x = long, y = lat, group = group), fill = "lightgray", color = "darkgreen")+
  geom_tile(alpha = 0.8) +
  coord_cartesian(xlim = c(-80, -55), ylim = c(32, 48))+
  theme(legend.position = 'right') + 
  labs(fill = "", x = "Longitude (in degrees)", y = "Latitude (in degrees)") + 
  geom_text(x = -75, y = 41.5, label = "The United States", color = "black", size = 8, 
            fontface = "bold", angle = 40) +
  geom_text(x = -75, y = 46.5, label = "Canada", color = "black", size = 8, fontface = "bold")

trawlzoomplot
```


```{r}
print(fitgam3)
```
```{r}
trawldata |>
  select(year, lon, lat, depth_avg, `wtcpue.Homarus americanus`, 
         `wtcpue.Crossaster papposus`, `wtcpue.Dfo:bryozoans ectoprocta`, `wtcpue.Neptunea lyrata`)
```




```{r}
trawldata |>
  select(year, lon, lat, depth_avg,
         `wtcpue.Homarus americanus`,
         `wtcpue.Crossaster papposus`,
         `wtcpue.Dfo:bryozoans ectoprocta`,
         `wtcpue.Neptunea lyrata`)
```










